export const Employees = [
    { month: 'Jan', Expenditure: 2890, Workers: 139, Hours: 4709 },
    { month: 'Feb', Expenditure: 2700, Workers: 176, Hours: 1017 },
    { month: 'Mar', Expenditure: 3600, Workers: 228, Hours: 376 },
    { month: 'Apr', Expenditure: 2500, Workers: 232, Hours: 6922 },
    { month: 'May', Expenditure: null, Workers: null, Hours: null },
    { month: 'Jun', Expenditure: null, Workers: null, Hours: null },
    { month: 'Jul', Expenditure: null, Workers: null, Hours: null },
    { month: 'Aug', Expenditure: 5000, Workers: null, Hours: null },
    { month: 'Sep', Expenditure: null, Workers: null, Hours: null },
    { month: 'Oct', Expenditure: null, Workers: null, Hours: null },
    { month: 'Nov', Expenditure: null, Workers: null, Hours: null },
    { month: 'Dec', Expenditure: null, Workers: null, Hours: null },
  ];

export const empAvailability = [
    { day: 'Mon', PT: 46, FT: 84 },
    { day: 'Tues', PT: 29, FT: 57 },
    { day: 'Wed', PT: 60, FT: 98 },
    { day: 'Thurs', PT: 47, FT: 26 },
    { day: 'Fri', PT: 80, FT: 95 },
    { day: 'Sat', PT: 50, FT: 78 },
    { day: 'Sun', PT: 50, FT: 59 },
  ];

export const monthlyBookings = [
    { month: 'Jan', Bookings: 46 },
    { month: 'Feb', Bookings: 29 },
    { month: 'Mar', Bookings: 60 },
    { month: 'Apr', Bookings: 47 },
    { month: 'May', Bookings: null },
    { month: 'Jun', Bookings: null },
    { month: 'Aug', Bookings: null },
    { month: 'Sep', Bookings: null },
    { month: 'Oct', Bookings: null },
    { month: 'Nov', Bookings: null },
    { month: 'Dec', Bookings: null },
  ];

  //displays customer demand forecast for the entire month
export const demandForecast = [
    { date: '1 Apr', Customers: 7350 },
    { date: '2 Apr', Customers: 9245 },
    { date: '3 Apr', Customers: 5185 },
    { date: '4 Apr', Customers: 8782 },
    { date: '5 Apr', Customers: 4457 },
    { date: '6 Apr', Customers: 4326 },
    { date: '7 Apr', Customers: 7847 },
    { date: '8 Apr', Customers: 6427 },
    { date: '9 Apr', Customers: 4068 },
    { date: '10 Apr', Customers: 5461 },
    { date: '11 Apr', Customers: 2735 },
    { date: '12 Apr', Customers: 6093 },
    { date: '13 Apr', Customers: 8815 },
    { date: '14 Apr', Customers: 6881 },
    { date: '15 Apr', Customers: 9658 },
    { date: '16 Apr', Customers: 6549 },
    { date: '17 Apr', Customers: 9263 },
    { date: '18 Apr', Customers: 3757 },
    { date: '19 Apr', Customers: 9451 },
    { date: '20 Apr', Customers: 5029 },
    { date: '21 Apr', Customers: 8932 },
    { date: '22 Apr', Customers: 7586 },
    { date: '23 Apr', Customers: 3707 },
    { date: '24 Apr', Customers: 5676 },
    { date: '25 Apr', Customers: 2214 },
    { date: '26 Apr', Customers: 9554 },
    { date: '27 Apr', Customers: 2594 },
    { date: '28 Apr', Customers: 6402 },
    { date: '29 Apr', Customers: 6940 },
    { date: '30 Apr', Customers: 7836 },
  ];