export const fakeEmployees = [
  {
    empId: 1,
    firstName: "Dylan",
    lastName: "Murray",
    mon: "9am to 10pm",
    tues: "9am to 6pm",
    wed: "9am to 10pm",
    thurs: "4pm to 10pm",
    fri: "9am to 10pm",
    sat: "NA",
    sun: "9am to 10pm",
  },
  {
    empId: 2,
    firstName: "Rachel",
    lastName: "Stone",
    mon: "9am to 3pm",
    tues: "NA",
    wed: "9am to 10pm",
    thurs: "12pm to 10pm",
    fri: "9am to 10pm",
    sat: "4pm to 10pm",
    sun: "9am to 10pm",
  },
]
